name: CB
options:
  bundleIdPrefix: com.otkrickey
  deploymentTarget:
    macOS: "26.2"
  xcodeVersion: "26.2"

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "26.2"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  CB:
    type: application
    platform: macOS
    sources:
      - path: CB/Sources
      - path: CB/Generated
        optional: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.otkrickey.cb
        INFOPLIST_FILE: CB/Resources/Info.plist
        SWIFT_OBJC_BRIDGING_HEADER: CB/BridgingHeader.h
        LIBRARY_SEARCH_PATHS:
          - "$(SRCROOT)/target/release"
          - "$(SRCROOT)/target/debug"
        OTHER_LDFLAGS:
          - "-lcb_core"
          - "-framework"
          - "Security"
          - "-framework"
          - "SystemConfiguration"
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        CODE_SIGNING_ALLOWED: "$(CB_CODE_SIGNING_ALLOWED)"
        CODE_SIGN_IDENTITY: "$(CB_CODE_SIGN_IDENTITY)"
        ENABLE_HARDENED_RUNTIME: "$(CB_ENABLE_HARDENED_RUNTIME)"
        CODE_SIGN_ENTITLEMENTS: CB/CB.entitlements
    preBuildScripts:
      - name: "Build Rust Library"
        script: |
          cd "$SRCROOT"
          if [ "$CONFIGURATION" = "Release" ]; then
            cargo build --release -p cb-core
          else
            cargo build -p cb-core
          fi
        basedOnDependencyAnalysis: false
